### ISSUE TITLE
500 error `/api/v1/refresh/token`

### ISSUE THREAD

**Issue by wyhfrank** [Chen33D17017/auto-invest-spring#21]
Message

``` 
error: "Internal Server Error"
path: "/api/v1/refresh/token"
status: 500
```

Stacktrace:
``` log
[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "String.split(String)" because "token" is null] with root cause

java.lang.NullPointerException: Cannot invoke "String.split(String)" because "token" is null
at com.auth0.jwt.TokenUtils.splitToken(TokenUtils.java:15) ~[java-jwt-3.18.3.jar!/:3.18.3]
at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:36) ~[java-jwt-3.18.3.jar!/:3.18.3]
at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:282) ~[java-jwt-3.18.3.jar!/:3.18.3]
at me.peihao.autoInvest.service.TokenService.verifyAndRegenerateTokenResponse(TokenService.java:79) ~[classes!/:0.0.1-SNAPSHOT]
at me.peihao.autoInvest.controller.AppUserController.refreshToken(AppUserController.java:62) ~[classes!/:0.0.1-SNAPSHOT]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
```

**Comment by Chen33D17017** [comment]
This is because the refresh token is null. Will deal with this case
