### ISSUE TITLE
System error when `GET` `/api/v1/user` if the length of`apiKey` or `apiSecret` is too short

### ISSUE THREAD

**Issue by wyhfrank** [Chen33D17017/auto-invest-spring#22]
The apiKey I registered is the string `"apiKey"`  with a length of 6. Might be the cause.

Stacktrace:

``` log
Caused by: java.lang.Exception: End index cannot be greater than start index
at me.peihao.autoInvest.service.AppUserService.maskString(AppUserService.java:187) ~[classes!/:0.0.1-SNAPSHOT]
at me.peihao.autoInvest.service.AppUserService.maskString(AppUserService.java:171) ~[classes!/:0.0.1-SNAPSHOT]
at me.peihao.autoInvest.service.AppUserService.getUserInfo(AppUserService.java:167) ~[classes!/:0.0.1-SNAPSHOT]
```

**Comment by wyhfrank** [comment]
Same issue as #19
